id: I9097C273
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:47:27+00:00'
last_modified: '2022-06-09T07:46:37.726108+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16726
  title: གཙང་པཎྜི་ཏ་བློ་བཟང་བསྟན་པ་རྒྱ་མཚོའི་རྣམ་ཐར་མདོར་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    1F24:
      image_group_id: I8LS16736
      title: Volume 1 of gtsang paN+Di ta blo bzang bstan pa rgya mtsho'i rnam thar
        mdor bsdus/
      total_pages: 66
      order: 1
      base_file: 1F24.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
