id: P007940
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS16726
  title: གཙང་པཎྜི་ཏ་བློ་བཟང་བསྟན་པ་རྒྱ་མཚོའི་རྣམ་ཐར་མདོར་བསྡུས།
  author: ''
  volumes:
    495bcb30a8334bfea49322f3a4a362fa:
      image_group_id: I8LS16736
      title: ''
      volume_number: 1
      total_pages: 66
ebook_metadata:
  title: གཙང་པཎྜི་ཏ་བློ་བཟང་བསྟན་པ་རྒྱ་མཚོའི་རྣམ་ཐར་མདོར་བསྡུས།
  author: ''
  sku: P007940
  cover: cover.jpg
  layers:
  - pagination
